"""Real MoSPI Airfare CPI vs our own Nowcasted APIx (Headline, total-fare, national),
rebased onto MoSPI's scale via a splice at the first calendar month both series cover.

Unlike the existing DGCA back-test - whose benchmark is generated by perturbing our own
index (see seeds/load_seed.py) - the MoSPI numbers here come from a real government
download (data/cpi_1703.xlsx, ingested by scripts/ingest_mospi_cpi.py into
`cpi_reference`) and this module never touches them. See
app/analytics/backtest/mospi_alignment.py for why a splice, not a direct overlay, is the
honest way to put two differently-based series on one chart, and IMPLEMENTATION_LOG.md
for the full writeup.
"""
from __future__ import annotations

from calendar import monthrange
from datetime import date, timedelta

from sqlalchemy.ext.asyncio import AsyncSession

from app.analytics.backtest import NoOverlapError, all_metrics, rebase_to_official
from app.analytics.index_engine import (
    compute_aggregate_index,
    compute_route_index,
    compute_route_measure,
)
from app.config import settings
from app.core.constants import Estimator
from app.db.repositories import analytics_repository as analytics_repo
from app.db.repositories import index_repository as index_repo

MOSPI_SERIES_VINTAGE = "mospi-airfare-2024"


def _month_start(d: date) -> date:
    return d.replace(day=1)


def _month_end(d: date) -> date:
    return d.replace(day=monthrange(d.year, d.month)[1])


def _next_month(d: date) -> date:
    return (_month_end(d) + timedelta(days=1)).replace(day=1)


async def _compute_monthly_headline(session: AsyncSession, months: list[date]) -> dict[date, float]:
    """Recomputes the national Headline (total-fare) index as a calendar-month average,
    for each month requested - same engine, base period and weight table as
    index_service.recompute_national(), just aggregated by month instead of a trailing
    7-day window. Deliberately independent of the pre-computed `index_values` table
    (which only covers the last ~120 days) so this can reach back to whenever real
    observations start."""
    estimator = Estimator(settings.default_estimator)
    routes = await analytics_repo.all_routes(session, basket_only=True)
    weights = await index_repo.active_weights(session)
    base_period = date.fromisoformat(settings.index_base_period)

    base_measures = {}
    for route in routes:
        base_fares = await index_repo.route_fares(
            session, route.route_id, date_from=base_period, date_to=base_period + timedelta(days=30)
        )
        m = compute_route_measure(route.route_code, base_fares, estimator, settings.min_observations_per_period)
        if m:
            base_measures[route.route_code] = m

    result: dict[date, float] = {}
    for month in months:
        route_indices = []
        for route in routes:
            base = base_measures.get(route.route_code)
            if base is None:
                continue
            fares = await index_repo.route_fares(
                session, route.route_id, date_from=_month_start(month), date_to=_month_end(month)
            )
            measure = compute_route_measure(
                route.route_code, fares, estimator, settings.min_observations_per_period
            )
            if measure is None:
                continue
            route_indices.append(compute_route_index(measure, base.value))

        aggregate = compute_aggregate_index(route_indices, weights)
        if aggregate:
            result[_month_start(month)] = aggregate.index_value

    return result


async def get_mospi_comparison(session: AsyncSession) -> dict | None:
    official_rows = [
        r
        for r in await analytics_repo.cpi_series(session, MOSPI_SERIES_VINTAGE)
        if r.airfare_sub_index is not None
    ]
    if not official_rows:
        return None

    official_monthly = {r.period_month: float(r.airfare_sub_index) for r in official_rows}

    today = date.today()
    months = []
    cursor = min(official_monthly)
    while cursor <= _month_start(today):
        months.append(cursor)
        cursor = _next_month(cursor)

    ours_monthly = await _compute_monthly_headline(session, months)

    try:
        rebased, anchor_month, scale_factor = rebase_to_official(ours_monthly, official_monthly)
    except NoOverlapError:
        return None

    overlap_months = sorted(set(rebased) & set(official_monthly))
    overlap_metrics = None
    if len(overlap_months) >= 2:
        overlap_metrics = all_metrics(
            [official_monthly[m] for m in overlap_months],
            [rebased[m] for m in overlap_months],
        )

    last_official_month = max(official_monthly)
    latest_nowcast_month = max(rebased) if rebased else None
    data_lag_days = (today - _month_end(last_official_month)).days

    points = [
        {
            "month": month,
            "official_index": official_monthly.get(month),
            "nowcast_index": rebased[month],
            "is_official": month in official_monthly,
        }
        for month in sorted(rebased)
    ]

    return {
        "series_vintage": MOSPI_SERIES_VINTAGE,
        "base_year": official_rows[0].base_year,
        "anchor_month": anchor_month,
        "scale_factor": scale_factor,
        "alignment_method": (
            "Our national Headline APIx, aggregated to a calendar-month mean, rescaled to "
            f"MoSPI's base by matching values at {anchor_month.strftime('%B %Y')} "
            f"(scale factor {scale_factor}). Month-over-month change of our own series is "
            "preserved exactly - only the price level is shifted to match MoSPI's base."
        ),
        "points": points,
        "overlap_months": len(overlap_months),
        "overlap_metrics": overlap_metrics,
        "last_official_month": last_official_month,
        "latest_nowcast_month": latest_nowcast_month,
        "data_lag_days": data_lag_days,
    }
