"""Rebasing between our index (base = BASE_PERIOD, see seeds/generate_seed.py) and the
real MoSPI Airfare CPI (base year 2024=100).

The two series are NOT on the same scale, and nothing else in this codebase reconciles
that (the existing DGCA back-test's "alignment" is purely temporal - see alignment.py -
and its benchmark is synthetic, generated by perturbing our own index, so the scale
problem never came up there). This module does the one honest thing possible: a splice
at the earliest month both series actually have real data for. The scale factor is
computed once, applied uniformly, and always returned alongside the result so it is
never hidden - see IMPLEMENTATION_LOG.md for why this needed its own module.

This is NOT curve-fitting or interpolation of missing values - every point that goes
into the scale factor and every point on both output lines is a real, observed value.
The only thing "interpolated" is the straight line ECharts draws between two adjacent
real monthly points, which is standard chart rendering, not synthesised data.
"""
from __future__ import annotations

from datetime import date


class NoOverlapError(ValueError):
    """Raised when the two series share no common month to splice at."""


def rebase_to_official(
    ours_monthly: dict[date, float], official_monthly: dict[date, float]
) -> tuple[dict[date, float], date, float]:
    """Rescale `ours_monthly` so it reads the same as `official_monthly` at the
    earliest month both series cover, preserving our own series' month-over-month
    percentage changes exactly - only the price LEVEL shifts, not the shape.

    Returns (rebased_series, anchor_month, scale_factor).
    """
    common = sorted(set(ours_monthly) & set(official_monthly))
    if not common:
        raise NoOverlapError("no overlapping month between our series and the MoSPI series")

    anchor = common[0]
    if ours_monthly[anchor] <= 0:
        raise NoOverlapError(f"our value at anchor month {anchor} is not positive")

    scale = official_monthly[anchor] / ours_monthly[anchor]
    rebased = {m: round(v * scale, 3) for m, v in ours_monthly.items()}
    return rebased, anchor, round(scale, 4)
